const result = await Bun.build({
  entrypoints: [new URL("../src/syncWorker.ts", import.meta.url).pathname],
  format: "iife",
  minify: true,
  sourcemap: "none",
  target: "browser",
});

if (!result.success || !result.outputs[0]) {
  throw new Error("Failed to bundle the PWA Sync service-worker runtime.");
}

const source = await result.outputs[0].text();
await Bun.write(
  new URL("../src/generatedSyncWorker.ts", import.meta.url),
  `// Generated by scripts/generateSyncWorker.ts. Do not edit.\nexport const syncWorkerBlock: string = ${JSON.stringify(source)};\n`,
);
